### ISSUE TITLE
Coursework / program requirements

### ISSUE THREAD

**Issue by lkwhite** [jayhesselberth/molbcu.org#11]
Currently this content is on the [Curriculum page](http://www.ucdenver.edu/academics/colleges/medicalschool/programs/Molbio/About/Pages/Curriculum.aspx) and in the handbook. How much should we carry over onto the new site? I think prospective students definitely want a sense of what year 1, year 2, years subsequent look like in a program. This is also a good place to delineate the timing and general structure of prelims and comps, as well as the lack of teaching requirement.

**Comment by lkwhite** [comment]
Also could fold in mention of the [Biomolecular Structure Track](http://www.ucdenver.edu/academics/colleges/medicalschool/programs/Molbio/About/Pages/BiomolStructure.aspx) onto this page. It's an asset that deserves highlighted, even if we're reducing the # of static pages overall.

**Comment by jayhesselberth** [comment]
I'm not sure these should be elevated to a separate main menu item. Perhaps they could be on the "About" page?

**Comment by jayhesselberth** [comment]
Closed by d37891688b61419a774e8d214aab383457e336c6
