### ISSUE TITLE
Benefits

### ISSUE THREAD

**Issue by lkwhite** [jayhesselberth/molbcu.org#14]
Where to put links for insurance, etc? We always get the pragmatic questions at recruitment when no PIs around, because people are trying work out what their life/budget would look like if they moved here. This spring during recruitment I fielded questions from multiple students about _parking costs_, for crying out loud. The more we make all the dollars and cents info available on the web page the more time we can devote during recruitment to actually selling them on the program and science being awesome.

**Comment by lkwhite** [comment]
Also I should get a raise for managing to strike an upbeat tone about our many! parking! options!

**Comment by jayhesselberth** [comment]
I think we should rename the "Denver" page to "Student Life" or similar. Then we can put this there.

**Comment by lkwhite** [comment]
And this is when our hero realizes she just inadvertently volunteered to write about campus parking.

**Comment by lkwhite** [comment]
**Stipend and benefits**
PhD students receive a stipend of $30,000 per year, paid in monthly installments on the last working day of each month. The Program also pays tuition, fees, and [health/dental insurance](http://www.ucdenver.edu/life/services/student-health/Pages/default.aspx) for the first year; these costs are paid by a student's chosen thesis mentor thereafter.

**Comment by emilydduncan** [comment]
is there any interest in having a "CU Anschutz" section? i've noticed some programs have this. talking about the different core facilities and resources available on campus that are unique...obviously having the hospital next door is of great interest to translational researchers, different departments/organizations/clubs, BEST program, no undergrads, etc. 

we could probably lump some of this into the student life section?

**Comment by jayhesselberth** [comment]
I think a campus section is probably better placed on the About page. The student life page is shaping up to be a catch-all for off-campus stuff.

@emilydduncan can you draft some language?

**Comment by emilydduncan** [comment]
@jayhesselberth @lkwhite 
this is what I have so far. I was thinking the first 3 paragraphs could be on the "overview" page with this picture 
![campus_anschutz](https://user-images.githubusercontent.com/40901713/42488456-e2eac334-83c2-11e8-9136-679da6419535.png)

and then the last two sections aren't super important but might be nice addition to "student life" page.
feel free to fix the fluffiness and/or organization.


The Molecular Biology Program is located at the CU Anschutz Medical Campus, one of four University of Colorado campuses serving the Rocky Mountain region. CU Anschutz is located just 6 miles east of downtown Denver in Colorado’s third largest city, Aurora. Not only is it one of the newest health sciences campuses in the nation, but it’s also the largest academic health center in the Rocky Mountain regional area. With funding totaling more than $450 million annually, CU Anschutz has become a national leader both in health care and life sciences research through a combination of teaching, research, and clinical facilities. The five health professional schools (School of Medicine, School of Dental Medicine, College of Nursing, Skaggs School of Pharmacy and Pharmaceutical Sciences, Colorado School of Public Health) and The Graduate School combine to offer more than 40 degree programs on campus. Graduate students of the Molecular Biology Program get a chance to interact with all of these different sectors of campus, leading to a highly interdisciplinary and collaborative training program. 

The size and capability of CU Anschutz give rise to its many resources for trainees. The large array of Departments, Centers, and Institutes provide state-of-the-art facilities, some of which include the Protein Production/MoAb/Tissue Culture Core, the Molecular Biology Service Center at Barbara Davis, the Flow Cytometry Shared Resource Facility, the Genomics and Microarray Core, and the Biological Mass Spectrometry Facility. A full list of the research core facilities at CU Anschutz can be found here. Of particular interest to the Molecular Biology program is the RNA Bioscience Initiative, founded in January 2016 with $20 million in funding from Dean’s Office of the University of Colorado School of Medicine. With the importance of RNA biology becoming increasingly more clear, the RBI has set specific aims to create and expand a vibrant center of discovery and innovation in RNA research, diagnostics and therapy at CU Anschutz. This includes a number of grant and fellowship opportunities for faculty, post-docs, and students with RNA-related research projects. 

In 2013, CU Anschutz was selected as one of ten universities nationwide for the NIH Broadening Experiences in Scientific and Scholarly Training (BESST) award, which has allowed our campus to develop professional training opportunities for post-docs and graduate students that will continue to be offered. Some of these opportunities include career seminars, workshops, boot camps, courses, and internships. You can visit the BESST website for more information or contact our BESST program Principle Investigator, Dr. Inge Wefes. 

The Anschutz Health and Wellness Center, located on campus, offers a monthly rate of $35 for students. More information on the facilities and programs offered can be found here.

Many current Molecular Biology students are involved in professional organizations across campus including CU Anschutz Women in STEM, SACNAS, PRISM, Graduate Student Council, Student Senate, and the Academic Industry Alliance. These student run organizations provide a multitude of opportunities to get involved in various leadership positions, community outreach, and graduate student advocacy.

**Comment by emilydduncan** [comment]
@jayhesselberth @lkwhite 
and of course all of my hyperlinks disappeared!

**Comment by emilydduncan** [comment]
[MOLB website content.docx](https://github.com/jayhesselberth/molbcu.org/files/2178773/MOLB.website.content.docx)
