### ISSUE TITLE
stipend

### ISSUE THREAD

**Issue by jayhesselberth** [jayhesselberth/molbcu.org#3]
I assume this is number has increased:

- Annual stipend: $28,500 (2015-2016)

**Comment by lkwhite** [comment]
We've crested the magic number of $30,000 (which I believe it's still at?). For all that that's not keeping up with COL, my understanding is they actually do a pretty good job of raising it every other academic year or so, so this is a piece of the website content that should be regularly revisited.

**Comment by emilydduncan** [comment]
can confirm 30,000 for 2017-2018. and also yes Laura I think you're right in that they are raising every other academic year
