### ISSUE TITLE
Update card layouts on mobile

### ISSUE THREAD

**Issue by jayhesselberth** [jayhesselberth/molbcu.org#5]

**Comment by lkwhite** [comment]
Also for browser. Can the layout for these cards cascade down on resize instead of being fixed at 4 cards/row?
<img width="947" alt="screen shot 2018-07-08 at 1 05 30 pm" src="https://user-images.githubusercontent.com/8239650/42423004-ac7f8a50-82af-11e8-80bb-651758815e75.png">

**Comment by jayhesselberth** [comment]
Yes, need to modify CSS.
